CREATE USER '${DATABASE_FORGEJO_USER}'@'%' IDENTIFIED BY '${DATABASE_FORGEJO_PASSWORD}';

CREATE DATABASE ${DATABASE_FORGEJO_DBNAME} CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin';

GRANT ALL PRIVILEGES ON  ${DATABASE_FORGEJO_DBNAME}.* TO '${DATABASE_FORGEJO_USER}';
FLUSH PRIVILEGES;
